### ISSUE TITLE
select functions not working

### ISSUE THREAD

**Issue by kyleupton** [husonlab/dendroscope3#3]
When using the select commands in the command input window, some of the commands listed in the manual are not working.

Message as follows:
Executing: select edges=all;
Command usage: select edges={all|none|long|short} [threshold=<number>]; - Select edges
Caught:
java.io.IOException: Line 1: any of 'all none short long' expected
    at jloda.util.parse.NexusStreamParser.matchAnyTokenIgnoreCase(Unknown Source)
    at dendroscope.commands.select.SelectEdgesCommand.apply(Unknown Source)
    at jloda.gui.commands.CommandManager.execute(Unknown Source)
    at jloda.gui.commands.CommandManager.execute(Unknown Source)
    at dendroscope.core.Director$2.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Executing: select nonterminal;
Failed to parse command: 'select'
Failed to parse command: 'nonterminal'

**Comment by husonlab** [comment]
Will upload a new version that fixes these issues
